# Generated by Django 5.1.4 on 2026-04-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('fonts', 'Шрифты'), ('moodboard', 'Мудборд'), ('colors', 'Цветовая палитра'), ('mixed', 'Смешанный')], default='mixed', max_length=20)),
                ('brief', models.TextField(blank=True, help_text='Начальный промпт пользователя')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
