# Generated by Django 5.1.4 on 2026-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_payload',
            field=models.JSONField(blank=True, help_text='Свёрнутая AI-рекомендация по проекту (шрифты, палитра, макет)', null=True),
        ),
    ]
