# Generated by Django 5.1.4 on 2026-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tag', models.CharField(default='Типографика', max_length=80)),
                ('hue', models.CharField(choices=[('cream', 'Крем'), ('mint', 'Мята'), ('lilac', 'Сирень'), ('peach', 'Персик'), ('sky', 'Небо')], default='cream', max_length=20)),
                ('cover', models.URLField(blank=True, help_text='URL обложки (опционально)')),
                ('excerpt', models.CharField(blank=True, max_length=320)),
                ('content', models.TextField(help_text='Markdown / обычный текст статьи')),
                ('author', models.CharField(default='Guidio', max_length=120)),
                ('read_minutes', models.PositiveIntegerField(default=4)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
