# Generated by Django 5.1.4 on 2026-05-11 17:23

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('Serif', 'Serif'), ('Sans-serif', 'Sans-serif'), ('Display', 'Display'), ('Script', 'Script'), ('Slab', 'Slab'), ('Monospace', 'Monospace')], max_length=20)),
                ('role', models.CharField(choices=[('Заголовок', 'Заголовок'), ('Текст', 'Текст'), ('Универсальный', 'Универсальный'), ('Только акцент', 'Только акцент')], max_length=20)),
                ('width', models.CharField(choices=[('Узкая', 'Узкая'), ('Обычная', 'Обычная'), ('Широкая', 'Широкая')], max_length=10)),
                ('usage_context', models.TextField(blank=True)),
                ('theme', models.TextField(blank=True)),
                ('character_mood', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('google_fonts', 'Google Fonts'), ('local', 'Локальный архив'), ('external', 'Внешняя ссылка')], max_length=20)),
                ('google_family', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='fonts/')),
                ('embedding_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FontPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_body', to='fonts.font')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_heading', to='fonts.font')),
            ],
            options={
                'ordering': ['heading__name', 'body__name'],
                'unique_together': {('heading', 'body')},
            },
        ),
    ]
